#Container base
FROM node:7.2-slim

# Crea la carpeta donde va a estar la app
RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/routes
WORKDIR /usr/src/app


# instala las d1ependencias del proyecto definidas en el package.json
COPY package.json /usr/src/app/
RUN npm install

# copia los archivos
COPY server.js /usr/src/app
COPY routes/wines.js /usr/src/app/routes

EXPOSE 3000
CMD [ "npm", "start" ]
